version: "3.7"

services:
  consul:
    image: consul
    container_name: consul
    restart: unless-stopped
    networks:
      - spirebyte
    ports:
      - 8500:8500
    # volumes:
    #   - consul:/consul/data

  fabio:
    image: fabiolb/fabio
    container_name: fabio
    restart: unless-stopped
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=consul:8500
    networks:
      - spirebyte
    ports:
      - 9998:9998
      - 9999:9999

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: unless-stopped
    networks:
      - spirebyte
    ports:
      - 5775:5775/udp
      - 5778:5778
      - 6831:6831/udp
      - 6832:6832/udp
      - 9411:9411
      - 14268:14268
      - 16686:16686

  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=4UeQAJgTqbCwjPCH
    networks:
      - spirebyte
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    restart: unless-stopped
    networks:
      - spirebyte
    ports:
      - 1433:1433
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y

  rabbitmq:
    build: ./rabbitmq
    container_name: rabbitmq
    restart: unless-stopped
    networks:
      - spirebyte
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    # volumes:
    #   - rabbitmq:/var/lib/rabbitmq

  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    networks:
      - spirebyte
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  seq:
    image: datalust/seq
    container_name: seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - spirebyte
    ports:
      - 5341:80
    # volumes:
    #   - seq:/data

  vault:
    image: vault
    container_name: vault
    restart: unless-stopped
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK
    networks:
      - spirebyte
    ports:
      - 8200:8200

  minio:
    image: minio/minio
    ports:
      - "9100:9100"
    volumes:
      - minio:/data
    networks:
      - spirebyte
    labels:
      - traefik.http.routers.storage.rule=Host(`storage.spirebyte.nl`)
      - traefik.http.routers.storage.entrypoints=websecure
      - traefik.http.services.storage.loadbalancer.server.port=9100
      - traefik.http.routers.storage.service=storage
      - traefik.http.routers.storage.tls=true
      - traefik.http.routers.storage.tls.certresolver=lets-encrypt
    environment:
      MINIO_ACCESS_KEY: a6qqJrzRsKXyCWBBAiTX
      MINIO_SECRET_KEY: FUszZfph3AqHRdB3kOwh
    command: server /data

networks:
  spirebyte:
    name: spirebyte-network

volumes:
  # consul:
  #   driver: local
  # grafana:
  #   driver: local
  mongo:
    driver: local
  minio:
    driver: local
  sqlserver:
    driver: local
  # prometheus:
  #   driver: local
  # rabbitmq:
  #   driver: local
  redis:
    driver: local
  # seq:
  #   driver: local
