version: "3.7"

services:
  spirebyte-consul:
    image: consul
    container_name: spirebyte-consul
    restart: unless-stopped
    networks:
      - spirebyte
    # ports:
    #   - 8500:8500
    # volumes:
    #   - consul:/consul/data

  spirebyte-fabio:
    image: fabiolb/fabio
    container_name: spirebyte-fabio
    restart: unless-stopped
    environment:
      - FABIO_REGISTRY_CONSUL_ADDR=spirebyte-consul:8500
    networks:
      - spirebyte
    # ports:
    #   - 9998:9998
    #   - 9999:9999

  spirebyte-jaeger:
    image: jaegertracing/all-in-one
    container_name: spirebyte-jaeger
    restart: unless-stopped
    networks:
      - spirebyte
    # ports:
    #   - 5775:5775/udp
    #   - 5778:5778
    #   - 6831:6831/udp
    #   - 6832:6832/udp
    #   - 9411:9411
    #   - 14268:14268
    #   - 16686:16686

  spirebyte-mongo:
    image: mongo
    container_name: spirebyte-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=4UeQAJgTqbCwjPCH
    networks:
      - spirebyte
    ports:
      - 27018:27017
    volumes:
      - spirebyte-mongo:/data/db

  spirebyte-rabbitmq:
    build: ./rabbitmq
    container_name: spirebyte-rabbitmq
    restart: unless-stopped
    networks:
      - spirebyte
    # ports:
    #   - 5672:5672
    #   - 15672:15672
    #   - 15692:15692
    # volumes:
    #   - rabbitmq:/var/lib/rabbitmq

  spirebyte-redis:
    image: redis
    container_name: spirebyte-redis
    restart: unless-stopped
    networks:
      - spirebyte
    # ports:
    #   - 6379:6379
    volumes:
      - spirebyte-redis:/data

  spirebyte-seq:
    image: datalust/seq
    container_name: spirebyte-seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
    networks:
      - spirebyte
    # ports:
    #   - 5341:80
    # volumes:
    #   - seq:/data

  spirebyte-vault:
    image: vault
    container_name: spirebyte-vault
    restart: unless-stopped
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_DEV_ROOT_TOKEN_ID=secret
    cap_add:
      - IPC_LOCK
    networks:
      - spirebyte
    # ports:
    #   - 8200:8200

  spirebyte-minio:
    image: minio/minio
    container_name: spirebyte-minio
    ports:
      - "9100:9100"
    volumes:
      - spirebyte-minio:/data
    networks:
      - spirebyte
    labels:
      - traefik.http.routers.storage.rule=Host(`storage.spirebyte.nl`)
      - traefik.http.routers.storage.entrypoints=websecure
      - traefik.http.services.storage.loadbalancer.server.port=9100
      - traefik.http.routers.storage.service=storage
      - traefik.http.routers.storage.tls=true
      - traefik.http.routers.storage.tls.certresolver=lets-encrypt
    environment:
      MINIO_ACCESS_KEY: a6qqJrzRsKXyCWBBAiTX
      MINIO_SECRET_KEY: FUszZfph3AqHRdB3kOwh
    command: server /data

networks:
  spirebyte:
    name: spirebyte-network

volumes:
  # consul:
  #   driver: local
  # grafana:
  #   driver: local
  spirebyte-mongo:
    driver: local
  spirebyte-minio:
    driver: local
  # prometheus:
  #   driver: local
  # rabbitmq:
  #   driver: local
  spirebyte-redis:
    driver: local
  # seq:
  #   driver: local
