version: "3.7"

services:
  spirebyte-api-gateway:
    image: ${DOCKER_REGISTRY-}spirebyteapigateway
    build: ../src/Gateway
    container_name: spirebyte-api-gateway
    restart: unless-stopped
    environment:
      - NTRADA_CONFIG=ntrada.docker
    ports:
      - 5000:80
    networks:
      - spirebyte

  spirebyte-identity-service:
    image: ${DOCKER_REGISTRY-}spirebyteservicesidentity
    build: ../src/Identity-Service
    container_name: spirebyte-identity-service
    restart: unless-stopped
    ports:
      - 5004:80
    networks:
      - spirebyte

  spirebyte-projects-service:
    image: ${DOCKER_REGISTRY-}spirebyteservicesprojects
    build: ../src/Project-Service
    container_name: spirebyte-projects-service
    restart: unless-stopped
    ports:
      - 5001:80
    networks:
      - spirebyte

  spirebyte-email-service:
    image: ${DOCKER_REGISTRY-}spirebyteservicesemail
    build: ../src/Email-Service
    container_name: spirebyte-email-service
    restart: unless-stopped
    ports:
      - 5002:80
    networks:
      - spirebyte

  spirebyte-issues-service:
    image: ${DOCKER_REGISTRY-}spirebyteservicesissues
    build: ../src/Issue-Service
    container_name: spirebyte-issues-service
    restart: unless-stopped
    ports:
      - 5003:80
    networks:
      - spirebyte

  spirebyte-sprints-service:
    image: ${DOCKER_REGISTRY-}spirebyteservicessprints
    build: ../src/Sprint-Service
    container_name: spirebyte-sprints-service
    restart: unless-stopped
    ports:
      - 5005:80
    networks:
      - spirebyte

  spirebyte-operations-service:
    image: ${DOCKER_REGISTRY-}spirebyteservicesoperations
    build: ../src/Operation-Service
    container_name: spirebyte-operations-service
    restart: unless-stopped
    ports:
      - 5006:80
    networks:
      - spirebyte


networks:
  spirebyte:
    name: spirebyte-network
    external: true