version: "3.7"

services:
  api-gateway:
    build: ../src/ApiGateways
    container_name: api-gateway
    restart: unless-stopped
    environment:
      - NTRADA_CONFIG=ntrada.docker
    ports:
      - 5000:80
    networks:
      - spirebyte

  identity-service:
    build: ../src/services/identity
    container_name: identity-service
    restart: unless-stopped
    ports:
      - 5004:80
    networks:
      - spirebyte

networks:
  spirebyte:
    name: spirebyte-network
    external: true