version: "3.7"

services:
  api-gateway:
    image: ${DOCKER_REGISTRY-}spirebyteapigateway
    build: ../src/ApiGateways
    container_name: api-gateway
    restart: unless-stopped
    environment:
      - NTRADA_CONFIG=ntrada.docker
      - USE_SSL=true
    ports:
      - 5000:80
      - 6000:443
    networks:
      - spirebyte

  identity-service:
    image: ${DOCKER_REGISTRY-}spirebyteservicesidentity
    build: ../src/Services/Identity
    container_name: identity-service
    restart: unless-stopped
    ports:
      - 5004:80
    networks:
      - spirebyte

  projects-service:
    image: ${DOCKER_REGISTRY-}spirebyteservicesprojects
    build: ../src/Services/Projects
    container_name: projects-service
    restart: unless-stopped
    ports:
      - 5001:80
    networks:
      - spirebyte

  email-service:
    image: ${DOCKER_REGISTRY-}spirebyteservicesemail
    build: ../src/Services/Email
    container_name: email-service
    restart: unless-stopped
    ports:
      - 5002:80
    networks:
      - spirebyte

  issues-service:
    image: ${DOCKER_REGISTRY-}spirebyteservicesissues
    build: ../src/Services/Issues
    container_name: issues-service
    restart: unless-stopped
    ports:
      - 5003:80
    networks:
      - spirebyte

  sprints-service:
    image: ${DOCKER_REGISTRY-}spirebyteservicessprints
    build: ../src/Services/Sprints
    container_name: sprints-service
    restart: unless-stopped
    ports:
      - 5005:80
    networks:
      - spirebyte


networks:
  spirebyte:
    name: spirebyte-network
    external: true